### ISSUE TITLE
Ez.

### ISSUE THREAD

**Issue by fikret0** [tixvage/scene-editor#1]
**ezpz.**

**Comment by kaankny** [comment]
oh0 çet ne diyor bu ya

**Comment by fikret0** [comment]
> oh0 çet ne diyor bu ya

aga obama gelıyo saklan

**Comment by kaankny** [comment]
kaç kaç

**Comment by tixvage** [comment]
lan noluyo

**Comment by tixvage** [comment]
anime çöptür konu kapandı sorun çözüldü.
